_wandb:
    value:
        cli_version: 0.21.0
        e:
            zr9qu1rvj65gwuf6tooyn0len18yepm1:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 8
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "11811160064"
                codePath: model/finetune/seed_dataset/scripts/validation.py
                codePathLocal: model/finetune/seed_dataset/scripts/validation.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "183635361792"
                email: spurwand@gmail.com
                executable: /usr/local/bin/python3
                git:
                    commit: 2d627a6f941d634685870bbf7e96f91eed800bdb
                    remote: https://github.com/shellamp/Thesis_PredictingNewsOutdatedness_Logistic_Decay.git
                host: 192.168.1.12
                memory:
                    total: "8589934592"
                os: macOS-15.5-arm64-arm-64bit
                program: /Users/sheillaschool/Documents/final/Thesis_PredictingNewsOutdatedness_Logistic_Decay/model/finetune/seed_dataset/scripts/validation.py
                python: CPython 3.12.0
                root: /Users/sheillaschool/Documents/final/Thesis_PredictingNewsOutdatedness_Logistic_Decay
                startedAt: "2025-07-15T14:23:35.281921Z"
                writerId: zr9qu1rvj65gwuf6tooyn0len18yepm1
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 13
            "4": 3.12.0
            "5": 0.21.0
            "12": 0.21.0
            "13": darwin-arm64
