_wandb:
    value:
        cli_version: 0.21.0
        e:
            7u3aczb8kjo1s2hucx2hlbc969jk4ulz:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 8
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "11811160064"
                codePath: model/labelling/scripts/rule_based/validation.py
                codePathLocal: model/labelling/scripts/rule_based/validation.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "183557496832"
                email: spurwand@gmail.com
                executable: /usr/local/bin/python3
                git:
                    commit: 6f7fc76929a22de702cba149577632c02d20e9a8
                    remote: https://github.com/shellamp/Thesis_PredictingNewsOutdatedness_Logistic_Decay.git
                host: 192.168.1.12
                memory:
                    total: "8589934592"
                os: macOS-15.5-arm64-arm-64bit
                program: /Users/sheillaschool/Documents/final/Thesis_PredictingNewsOutdatedness_Logistic_Decay/model/labelling/scripts/rule_based/validation.py
                python: CPython 3.12.0
                root: /Users/sheillaschool/Documents/final/Thesis_PredictingNewsOutdatedness_Logistic_Decay
                startedAt: "2025-07-15T15:15:18.707205Z"
                writerId: 7u3aczb8kjo1s2hucx2hlbc969jk4ulz
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 13
            "4": 3.12.0
            "5": 0.21.0
            "12": 0.21.0
            "13": darwin-arm64
